apiVersion: v1
kind: Service
metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 80 # default : same as port
      port: 80 # TODO : mandatory
      nodePort: 30008 # default : valid range between 30000 ~ 32767
  selector: # TODO : links to a pod with the same labels.app
    app: myapp
    type: front-end